const SYNONYMS: Record<string, string> = {
  hypr: "hyprland",
  hyprland: "hyprland",
  sway: "sway",
  swayfx: "swayfx",
  "sway-fx": "swayfx",
  niri: "niri",
  river: "river",
  wayfire: "wayfire",
  labwc: "labwc",
  cage: "cage",
  miracle: "miracle-wm",
  "miracle-wm": "miracle-wm",
  dwl: "dwl",
  weston: "weston",
  i3: "i3",
  "i3-gaps": "i3",
  i3gaps: "i3",
  bspwm: "bspwm",
  dwm: "dwm",
  awesome: "awesome",
  awesomewm: "awesome",
  xmonad: "xmonad",
  qtile: "qtile",
  herbstluftwm: "herbstluftwm",
  openbox: "openbox",
  leftwm: "leftwm",
  icewm: "icewm",
  fluxbox: "fluxbox",
  jwm: "jwm",
  berry: "berry",
  yabai: "yabai",
  aerospace: "aerospace",
  amethyst: "amethyst",
  gnome: "gnome",
  "gnome-shell": "gnome",
  kde: "kde-plasma",
  plasma: "kde-plasma",
  "kde plasma": "kde-plasma",
  "kde-plasma": "kde-plasma",
  xfce: "xfce",
  xfce4: "xfce",
  cinnamon: "cinnamon",
  mate: "mate",
  lxqt: "lxqt",
  budgie: "budgie",
  cosmic: "cosmic",
  pantheon: "pantheon",
  elementary: "pantheon",
  deepin: "deepin",
  dde: "deepin",
  enlightenment: "enlightenment",
  e16: "enlightenment",
  e17: "enlightenment",
  trinity: "trinity",
  tde: "trinity",
  kwin: "kwin",
  mutter: "mutter",
  xfwm: "xfwm",
  picom: "picom",
  compton: "picom",
  arch: "arch-linux",
  "arch linux": "arch-linux",
  archlinux: "arch-linux",
  "arch-linux": "arch-linux",
  endeavour: "endeavouros",
  endeavouros: "endeavouros",
  "endeavour os": "endeavouros",
  garuda: "garuda",
  manjaro: "manjaro",
  cachy: "cachyos",
  cachyos: "cachyos",
  artix: "artix",
  nixos: "nixos",
  nix: "nixos",
  fedora: "fedora",
  debian: "debian",
  ubuntu: "ubuntu",
  popos: "pop-os",
  "pop-os": "pop-os",
  "pop!_os": "pop-os",
  "pop os": "pop-os",
  mint: "linux-mint",
  "linux mint": "linux-mint",
  "linux-mint": "linux-mint",
  elementaryos: "elementary-os",
  "elementary os": "elementary-os",
  "elementary-os": "elementary-os",
  void: "void-linux",
  "void linux": "void-linux",
  "void-linux": "void-linux",
  gentoo: "gentoo",
  alpine: "alpine",
  opensuse: "opensuse",
  "open suse": "opensuse",
  rocky: "rocky",
  "rocky linux": "rocky",
  alma: "alma",
  alama: "alma",
  almalinux: "alma",
  "alma linux": "alma",
  centos: "centos",
  slackware: "slackware",
  solus: "solus",
  guix: "guix",
  "guix system": "guix",
  freebsd: "freebsd",
  openbsd: "openbsd",
  netbsd: "netbsd",
  macos: "macos",
  "mac os": "macos",
  darwin: "macos",
  osx: "macos",
  catppuccin: "catppuccin",
  gruvbox: "gruvbox",
  nord: "nord",
  "tokyo night": "tokyo-night",
  tokyonight: "tokyo-night",
  "tokyo-night": "tokyo-night",
  pywal: "pywal",
  wal: "pywal",
  everforest: "everforest",
  dracula: "dracula",
  rose: "rose-pine",
  "rose pine": "rose-pine",
  "rose-pine": "rose-pine",
  kanagawa: "kanagawa",
  onedark: "onedark",
  "one dark": "onedark",
  kitty: "kitty",
  wezterm: "wezterm",
  alacritty: "alacritty",
  foot: "foot",
  ghostty: "ghostty",
  konsole: "konsole",
  "gnome-terminal": "gnome-terminal",
  warp: "warp",
  tilix: "tilix",
  terminator: "terminator",
  "xfce4-terminal": "xfce4-terminal",
  "xfce terminal": "xfce4-terminal",
  st: "st",
  suckless: "st",
  urxvt: "urxvt",
  rxvt: "urxvt",
  "rxvt-unicode": "urxvt",
  xterm: "xterm",
  helix: "helix",
  hx: "helix",
  micro: "micro",
  waybar: "waybar",
  polybar: "polybar",
  eww: "eww",
  ags: "ags",
  age: "ags",
  hyprpanel: "hyprpanel",
  ironbar: "ironbar",
  tint2: "tint2",
  "latte-dock": "latte-dock",
  latte: "latte-dock",
  rofi: "rofi",
  wofi: "wofi",
  fuzzel: "fuzzel",
  tofi: "tofi",
  dmenu: "dmenu",
  dunst: "dunst",
  mako: "mako",
  swaync: "swaync",
  "sway-notification-center": "swaync",
  neovim: "neovim",
  nvim: "neovim",
  vim: "vim",
  emacs: "emacs",
  vscode: "vscode",
  code: "vscode",
  "vs code": "vscode",
  vscodium: "vscodium",
  codium: "vscodium",
  zed: "zed",
  kakoune: "kakoune",
  kak: "kakoune",
  sublime: "sublime",
  "sublime-text": "sublime",
  kate: "kate",
  zsh: "zsh",
  fish: "fish",
  bash: "bash",
  nushell: "nushell",
  nu: "nushell",
  xonsh: "xonsh",
  elvish: "elvish",
  tcsh: "tcsh",
  starship: "starship",
  tmux: "tmux",
  firefox: "firefox",
  zen: "zen-browser",
  "zen-browser": "zen-browser",
  chromium: "chromium",
  chrome: "chromium",
  brave: "brave",
  librewolf: "librewolf",
  qutebrowser: "qutebrowser",
  vivaldi: "vivaldi",
  floorp: "floorp",
  thunar: "thunar",
  dolphin: "dolphin",
  nautilus: "nautilus",
  yazi: "yazi",
  pcmanfm: "pcmanfm",
  nemo: "nemo",
  ranger: "ranger",
  lf: "lf",
  nnn: "nnn",
  superfile: "superfile",
  superifle: "superfile",
  sddm: "sddm",
  gdm: "gdm",
  lightdm: "lightdm",
  greetd: "greetd",
};

export function slugify(raw: string): string {
  const trimmed = raw.trim().toLowerCase().replace(/\s+/g, "-");
  const collapsed = trimmed.replace(/[^a-z0-9-]/g, "").replace(/-+/g, "-");
  return collapsed.replace(/^-|-$/g, "");
}

export function canonicalSlug(raw: string): string {
  const key = raw.trim().toLowerCase();
  if (SYNONYMS[key]) {
    return SYNONYMS[key];
  }
  const dashed = slugify(raw);
  if (SYNONYMS[dashed]) {
    return SYNONYMS[dashed];
  }
  const spaced = key.replace(/-/g, " ");
  if (SYNONYMS[spaced]) {
    return SYNONYMS[spaced];
  }
  return dashed;
}

export function labeledFrom(raw: string): { label: string; slug: string } {
  const slug = canonicalSlug(raw);
  const label = raw.trim() || slug;
  return { label, slug };
}
